### PR TITLE
fixes problem with wampcradynamic/python example

### PR DESCRIPTION
**Pull request by ghost**
subscription handler always show the same result

### CODE REVIEW

**Comment by goeddea** [comment]
Sorry for getting around to this so late. 

Thanks for the fix!

**Comment by oberstet** [comment]
this fix is wrong. please backout

**Comment by goeddea** [comment]
Undid.

**Comment by ghost** [comment]
did you try to run that example and see the result ?

**Comment by goeddea** [comment]
Looking closer at the print statement (combined with Tobias' comment), the intention here is to log that an event has been received on a particular topic, not the payload for said event. The same subscription handler is used for more than one topic, so this makes sense.

**Pull request merged**
