### PR TITLE
Fix Django example

### PR DESCRIPTION
**Pull request by om26er**
- The example was not able to load autobahn.min.js, fix that
- Remove deprecation warning

### CODE REVIEW

**Comment by om26er** [comment]
@goeddea Can you take a look at this one, please.

**Comment by om26er** [comment]
Adding @sametmax in the loop as well, as I just learned he is the one that contributed this example.

**Comment by sametmax** [comment]
I did but I don't have commit rights so I can't merge this :)

**Comment by om26er** [comment]
@sametmax So does the change look good to you ?

**Comment by ksamuel** [comment]
Yes,I didn't try to run it but  I can see you took care of up the template setting for the more recent version of django. Tobias merged it way before I had a look though :)

**Pull request merged**
