### PR TITLE
Add RPC ABJS

### PR DESCRIPTION
**Pull request by codelectron**
ABJS which works with both browser and nodejs
removed receive count

### CODE REVIEW

**Comment by oberstet** [comment]
ABJS is already in the repo: https://github.com/crossbario/crossbar-examples/tree/master/_shared-web-resources/autobahn

**Comment by codelectron** [comment]
Yes but this is only for the getting-started, where it can be directly opened in the browser as file. 
Also  the previous example in the getting-started has its own - https://github.com/crossbario/crossbar-examples/tree/master/getting-started. 

In my opinion,for getting-started examples  all the code confined to the same folder will bring clarity. 
What do you think?

**Comment by oberstet** [comment]
> examples all the code confined to the same folder will bring clarity

yes, I agree.

however, the downside being: lots of copies of ABJS - possibly in different versions.

further alternatives:

* use ABJS from here https://www.npmjs.com/package/autobahn-browser (add a `package.json` and have the use run `npm install`).
* (again) host ABJS on our sites and link to that from the demos. compared to the past, we now have all our site contents hosted via AWS CDN (cloudfront), so no worries about load

@goeddea what's you opinion?

**Comment by goeddea** [comment]
I think the argument for the getting started holds water: we do not want to introduce any unnecessary complexity here.

We should have automation to replace autobahn files on updates.

**Pull request merged**
