### PR TITLE
Updating csharp example

### PR DESCRIPTION
**Pull request by darkl**
In this [issue](https://github.com/Code-Sharp/WampSharp/issues/189) @alek5k brought to my attention that the csharp example is very outdated. I updated the dependencies and now it works. I also modified the code a bit, but if you don't like it I can revert it.
I also added a dotnet core sample which should work also on Ubuntu and Mac.

Thanks,
Elad

### CODE REVIEW

**Comment by oberstet** [comment]
@darkl Thx Elad! Awesome that you took the time to fix and polish up our example here to this degree=) Nice.

---

Let me take the chance to dump some thoughts: recently, I've become a big fan of starting development of new WAMP components as Docker images, like for example this: https://github.com/crossbario/crossbar-starter/tree/master/autobahn-js

One of the nice things is: the complete toolchain and/or run-time for a specific WAMP language / library comes as a Docker base image. Me, as a mere developer, simply uses or derives from that.

I am talking about this, because I thought: why didn't we notice earlier on that our WampSharp examples are broken?

Well, apart from the obvious (the sheer amount of code and pieces, and the limits of what we can really grok): let alone thinking about "quickly try it" makes me feel dizzy .. noooo, I don't want to feel the install/setup pain, going through, just for trying this.

Maybe this is a personal thing, but if it would be as easy as "docker run wamp-sharp", chances are that I'd do it;) Anyway, maybe food for thought.

FWIW, our own Docker images (more than 60): https://github.com/crossbario/crossbar-docker/blob/master/IMAGES.md

**Comment by alek5k** [comment]
@oberstet Hi Tobias, just to add to this suggestion, maybe some cross language unit/integration testing (eg. python to C#, python to java, java to C#, etc) would also be good? I guess that responsibility may fall onto the library maintainers, unless crossbar is willing to have these tests in its own repo. This would have picked up the issue pretty quickly in my case. After all, cross platform / cross language is what crossbar is all about! Food for thought.

**Comment by oberstet** [comment]
@alek5k We have an unfinished, internal integration test system ("crossbar-testrig")) that aims to be able to test across languages, run-times and platforms. I fully agree, given the goals and scope that WAMP has, this is quite important, and it runs beyond unit tests (those are good/necessary too of course). And we will take up development on this again! A full blown testrig is non-trivial/lots of work - I know, as eg AutobahnTestsuite was originally just a quick thing to aid my own implementation - turned out to be _lots_ of work to do it right. It paid off big time I'd say - for the WebSocket ecosystem in general (nearly the whole industry seems to be using it nowerdays), but we need to focus our limited resources ..

**Comment by darkl** [comment]
Not sure I understand docker yet, but [here](https://github.com/WampSharp/WampSharp-docker) are docker "templates" for a WampSharp client and a WampSharp router.

**Pull request merged**
