### PR TITLE
proxy worker example

### PR DESCRIPTION
**Pull request by meejah**

### CODE REVIEW

**Comment by oberstet** [comment]
+1

however .. I am running into this (this is CB log showing 2 failed attempts of `client.py` trying to connect):

```
2019-10-31T09:17:54+0100 [Controller  25437] Ok, local node configuration booted successfully!
2019-10-31T09:17:58+0100 [Proxy       25473] frontend: onConnect: {"peer": "tcp4:127.0.0.1:49894", "headers": {"user-agent": "AutobahnPython/19.10.2", "host": "localhost:8443", "upgrade": "WebSocket", "connection": "Upgrade", "pragma": "no-cache", "cache-control": "no-cache", "sec-websocket-key": "qcv9vV0kSZ/qjr2P57aLbw==", "sec-websocket-protocol": "wamp.2.json,wamp.2.cbor", "sec-websocket-version": "13"}, "host": "localhost", "path": "/ws", "params": {}, "version": 13, "origin": "", "protocols": ["wamp.2.json", "wamp.2.cbor"], "extensions": []}
2019-10-31T09:17:58+0100 [Proxy       25473] Frontend.onConnect(): request protocols: ['wamp.2.json', 'wamp.2.cbor']
2019-10-31T09:17:58+0100 [Proxy       25473] found config: {'transport': {'type': 'rawsocket', 'endpoint': {'type': 'unix', 'path': 'router.sock'}, 'url': 'rs://localhost', 'serializer': 'json'}, 'id': 'backend000'}
2019-10-31T09:17:58+0100 [Proxy       25473] found config: {'type': 'rawsocket', 'endpoint': {'type': 'unix', 'path': 'router.sock'}, 'url': 'rs://localhost', 'serializer': 'json'}
2019-10-31T09:17:58+0100 [Proxy       25473] Starting factory <autobahn.twisted.rawsocket.WampRawSocketClientFactory object at 0x7f3df33e05d0>
2019-10-31T09:17:58+0100 [Router      25449] WampRawSocketServerProtocol: opening handshake - no suitable serializer found (client requested 1, and we have dict_keys([3])
2019-10-31T09:17:58+0100 [Router      25449] Unhandled Error
Traceback (most recent call last):
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/internet/unix.py", line 191, in doRead
    return self._dataReceived(data)
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/rawsocket.py", line 285, in dataReceived
    self.abort()
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/rawsocket.py", line 226, in abort
    raise TransportLost()
autobahn.wamp.exception.TransportLost: 

2019-10-31T09:17:58+0100 [Proxy       25473] Stopping factory <autobahn.twisted.rawsocket.WampRawSocketClientFactory object at 0x7f3df33e05d0>
2019-10-31T09:18:11+0100 [Proxy       25473] frontend: onConnect: {"peer": "tcp4:127.0.0.1:49900", "headers": {"user-agent": "AutobahnPython/19.10.2", "host": "localhost:8443", "upgrade": "WebSocket", "connection": "Upgrade", "pragma": "no-cache", "cache-control": "no-cache", "sec-websocket-key": "ytIw6s3xolDiUQmcdaHzeg==", "sec-websocket-protocol": "wamp.2.json,wamp.2.cbor", "sec-websocket-version": "13"}, "host": "localhost", "path": "/ws", "params": {}, "version": 13, "origin": "", "protocols": ["wamp.2.json", "wamp.2.cbor"], "extensions": []}
2019-10-31T09:18:11+0100 [Proxy       25473] Frontend.onConnect(): request protocols: ['wamp.2.json', 'wamp.2.cbor']
2019-10-31T09:18:11+0100 [Proxy       25473] found config: {'transport': {'type': 'rawsocket', 'endpoint': {'type': 'unix', 'path': 'router.sock'}, 'url': 'rs://localhost', 'serializer': 'json'}, 'id': 'backend000'}
2019-10-31T09:18:11+0100 [Proxy       25473] found config: {'type': 'rawsocket', 'endpoint': {'type': 'unix', 'path': 'router.sock'}, 'url': 'rs://localhost', 'serializer': 'json'}
2019-10-31T09:18:11+0100 [Proxy       25473] Starting factory <autobahn.twisted.rawsocket.WampRawSocketClientFactory object at 0x7f3df33fd350>
2019-10-31T09:18:11+0100 [Router      25449] WampRawSocketServerProtocol: opening handshake - no suitable serializer found (client requested 1, and we have dict_keys([3])
2019-10-31T09:18:11+0100 [Router      25449] Unhandled Error
Traceback (most recent call last):
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
--- <exception caught here> ---
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
    why = selectable.doRead()
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/internet/unix.py", line 191, in doRead
    return self._dataReceived(data)
  File "/home/oberstet/cpy374_1/lib/python3.7/site-packages/twisted/internet/tcp.py", line 249, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/rawsocket.py", line 285, in dataReceived
    self.abort()
  File "/home/oberstet/scm/crossbario/autobahn-python/autobahn/twisted/rawsocket.py", line 226, in abort
    raise TransportLost()
autobahn.wamp.exception.TransportLost: 

2019-10-31T09:18:11+0100 [Proxy       25473] Stopping factory <autobahn.twisted.rawsocket.WampRawSocketClientFactory object at 0x7f3df33fd350>
```

**Comment by oberstet** [comment]
@meejah two more Qs .. what do you think?

* currently, the `backends` are defined in the `proxy` configuration at the worker level. should we move that to the (incoming) transport level? eg to `transports[0].paths["ws"].backends` ?
* currently, the `websocket` webservice configured on path `/ws` has `type=="websocket"` - exactly the same as existing one, even though it operates differently, as it proxy-forwards to backend connections (currently configured at the worker level). should we probably rename the new webservice to `type=="websocket-proxy"`?

as in (above 2 changes applied to the current example):

https://gist.github.com/oberstet/90849fc9f5534de85398ec837157bdc5

**Comment by meejah** [comment]
Definitely the second point makes a lot of sense ("same name, different function" is bad). Let me digest the first one some more :)

**Comment by meejah** [comment]
If we do make the change to put the proxy transports in a different spot, does it make sense to try and get rid of the (second) "transport" too? Like this:

```
                            "backends": [
                                {
                                    "type": "rawsocket",
                                    "endpoint": {
                                        "type": "unix",
                                        "path": "router.sock"
                                    },
                                    "url": "rs://localhost",
                                    "serializer": "json"
                                }
                            ]
```

(I guess I'm a little less sure about this change .. on the one hand, having the "backends" list gives them a bit more visibility .. but on the other hand, they are another list of "transport things" so why NOT have them alongside the others)

**Comment by oberstet** [comment]
not sure I get the idea with "getting rid of 2nd transport" ..

for the `transport[type=="websocket.proxy"].backends` configuration item, a full blown variant (in the "backends-per-transport" approach) could IMO look like

```json
"backends":
    {
        "foo": [
            {
                "type": "rawsocket",
                "endpoint": {
                    "type": "unix",
                    "path": "router.sock"
                },
                "url": "rs://localhost",
                "serializer": "cbor"
            }
        ],
        "realm1": [
            {
                "type": "websocket",
                "endpoint": {
                    "type": "unix",
                    "path": "routerws.sock"
                },
                "url": "rs://localhost",
                "serializers": ["json"]
            }
        ]
    }
```

The idea is:

* once HELLO was received on a new incoming connection, the proxy knows the `realm` a client wants to connect to.
* The proxy will (randomly) select any backend transport from the list of transports configured for the realm name used as key.
* For now, the proxy will create exactly 1 completely new backend connection per incoming client connection - and use the selected `transport` configuration to create the new backend connection
* Looking forward, once we have MUXed (backend) transport WAMP support, the proxy could keep a pool of MUXed backend connections and forward new incoming WAMP connections to backend connections already in the pool

**Comment by oberstet** [comment]
IOW, the configuration in `backends[<realm>] | list of <transport>` where `transport` is a connecting WAMP transport configuration determines the backend connections that are to be used. (I haven't thought about how that would ring with MUXed transports - once we have those ..)

**Comment by meejah** [comment]
I meant this "transport": https://gist.github.com/oberstet/90849fc9f5534de85398ec837157bdc5#file-config-alt-json-L279

**Comment by meejah** [comment]
I don't have particularly strong feelings either way .. I guess one thing that's different is that "backends" are client-type connections whereas the things (currently) in the "transports" section are all server-type/listening connections (right?)

**Comment by oberstet** [comment]
> I meant this "transport": ..

I don't see how we could get rid of that? The example has 2 proxy workers defined, and each configuration item needs to contain definitions of at least 1 backend transport - even if the same backend transport had already been defined in another worker.

> sidenote: we would need to define "references" as a concept for node configuration files first I think .. then we could define a backend transport only once, but reference it multiple times. however, that would be a bigger thing - and more so: I think a better approach is to push this "meta level" config burden to "crossbarfx master" ..

---

> I don't have particularly strong feelings either way .. whereas the things (currently) in the "transports" section are all server-type/listening connections (right?)

yes, but only "mostly";)

eg we already have "reverse web proxy" as a webservice, and the WAMP Application Template (WAP) webservices also have stuff pointing to "backends" (the WAMP proc to be called when a WAP page is rendered).

so there is "precedence" for defining stuff pointing to "backends" in items under a transport.

IOW: I would opt for putting backends into the "websocket-proxy" item(s) in the listening web transport (what I posted https://github.com/crossbario/crossbar-examples/pull/128#issuecomment-548277967). Reason being: I believe this will provide us useful flexibility looking forward. So if you don't care much, I'd opt for this one ..

**Comment by meejah** [comment]
okay, I fixed the original issue here (mismatched serializers basically) here: https://github.com/crossbario/crossbar-examples/pull/130

For the config changes, I'll do a crossbar PR first, then another one here..

**Comment by meejah** [comment]
Oh, I missed this before: in the example as written above, the backends are dicts with the realm-name as key. But, this means there's no way to provide a "default" backend. What about:
```
                        "ws": {
                            "type": "websocket-proxy",
                            "serializers": [
                                "cbor", "msgpack", "json"
                            ],
                            "backends": [
                                {
                                    "type": "websocket",
                                    "endpoint": {
                                        "type": "unix",
                                        "path": "routerws.sock"
                                    },
                                    "url": "ws://localhost",
                                    "serializers": ["json"]
                                },
                                {
                                    "type": "websocket",
                                    "realm": "realm1",
                                    "endpoint": {
                                        "type": "unix",
                                        "path": "routerws.sock"
                                    },
                                    "url": "ws://localhost",
                                    "serializers": ["json"]
                                }
                            ],
```

That is, the backends are just a list of dicts and they have an **optional** `"realm"` parameter. The backend with no realm is the "default" one. This simplifies configuration for the case where you have just one backend (but, e.g., several realms) and allows you to easily filter on realms (while also having a fallback / catchall).

**Comment by oberstet** [comment]
cool! looks good!

I just tested the example again, but had to do one fix:

https://github.com/crossbario/crossbar-examples/commit/c352935d7406ca1d5b8e5ee569e91949018a6f34

then, it "sometimes works", as in, sometimes, a client won't get properly connected and "just hangs":

```
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar-examples/proxy$ python client.py 
2019-11-07T12:25:25+0100 connecting once using transport type "websocket" over endpoint "tcp"
2019-11-07T12:25:25+0100 Starting factory <autobahn.twisted.websocket.WampWebSocketClientFactory object at 0x7f5acefc4810>
^C2019-11-07T12:25:33+0100 Received SIGINT, shutting down.
2019-11-07T12:25:33+0100 Session disconnected uncleanly
2019-11-07T12:25:33+0100 Connection failed: ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2019-11-07T12:25:33+0100 Stopping factory <autobahn.twisted.websocket.WampWebSocketClientFactory object at 0x7f5acefc4810>
2019-11-07T12:25:33+0100 Main loop terminated.
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar-examples/proxy$ python client.py 
2019-11-07T12:25:34+0100 connecting once using transport type "websocket" over endpoint "tcp"
2019-11-07T12:25:34+0100 Starting factory <autobahn.twisted.websocket.WampWebSocketClientFactory object at 0x7f2f94af9a50>
^C2019-11-07T12:25:39+0100 Received SIGINT, shutting down.
2019-11-07T12:25:39+0100 Session disconnected uncleanly
2019-11-07T12:25:39+0100 Connection failed: ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.
2019-11-07T12:25:39+0100 Stopping factory <autobahn.twisted.websocket.WampWebSocketClientFactory object at 0x7f2f94af9a50>
2019-11-07T12:25:39+0100 Main loop terminated.
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar-examples/proxy$ python client.py 
2019-11-07T12:25:40+0100 connecting once using transport type "websocket" over endpoint "tcp"
2019-11-07T12:25:40+0100 Starting factory <autobahn.twisted.websocket.WampWebSocketClientFactory object at 0x7fa18ef66910>
2019-11-07T12:25:40+0100 joined: <autobahn.twisted.wamp.Session object at 0x7fa18efa4b10>
2019-11-07T12:25:40+0100 subscribed
2019-11-07T12:25:40+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:25:40+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:25:41+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:25:41+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:25:42+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:25:42+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:25:43+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:25:43+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:25:44+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:25:44+0100 foo: (1, 2) {'foo': 'bar'}
^C2019-11-07T12:25:45+0100 Received SIGINT, shutting down.
2019-11-07T12:25:45+0100 session leaving 'wamp.close.transport_lost'
2019-11-07T12:25:45+0100 wamp.close.transport_lost: 
2019-11-07T12:25:45+0100 Stopping factory <autobahn.twisted.websocket.WampWebSocketClientFactory object at 0x7fa18ef66910>
2019-11-07T12:25:45+0100 Main loop terminated.
```

not sure what's happening .. have you seen this behavior? anything to try?

**Comment by oberstet** [comment]
in cases where a client does indeed successfully connect, then it does work, even with more than 1 client:

```
(cpy374_1) oberstet@intel-nuci7:~/scm/crossbario/crossbar-examples/proxy$ python client.py 
2019-11-07T12:28:43+0100 connecting once using transport type "websocket" over endpoint "tcp"
2019-11-07T12:28:43+0100 Starting factory <autobahn.twisted.websocket.WampWebSocketClientFactory object at 0x7fdf18cbfa50>
2019-11-07T12:28:43+0100 joined: <autobahn.twisted.wamp.Session object at 0x7fdf18cfdd10>
2019-11-07T12:28:43+0100 subscribed
2019-11-07T12:28:43+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:28:43+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:28:44+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:28:44+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:28:45+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:28:45+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:28:46+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:28:46+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:28:47+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:28:47+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:28:48+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:28:48+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:28:49+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:28:49+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:28:50+0100 publish to 'io.crossbar.demo.public.foo'
2019-11-07T12:28:50+0100 foo: (1, 2) {'foo': 'bar'}
2019-11-07T12:28:51+0100 foo: (1, 2) {'foo': 'bar'}
```

**Comment by meejah** [comment]
Hmm, I'll look more .. likely one of the two configured is working, and the other isn't? (so depends which on you happen to hit)

**Pull request merged**
