### PR TITLE
Further REST bridge examples

### PR DESCRIPTION
**Pull request by hawkowl**
Pusher -> Publisher, REST callee/subscriber examples

### CODE REVIEW

**Comment by oberstet** [comment]
Oh, I've already done part of that: https://github.com/crossbario/crossbarexamples/tree/master/rest
Could you add the subscriber example to this?

**Comment by hawkowl** [comment]
Oh huh. Whoops! I'll add the subscriber example in and reissue the PR

**Comment by hawkowl** [comment]
@oberstet how's this diff look?

**Comment by oberstet** [comment]
ah yes, great!

**Pull request merged**
